version: '3.8'

services:
  webapi:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SeuBancoDeDados;User=sa;Password=root

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "root"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    # Connection String: Server=sqlserver;Database=SeuBancoDeDados;User=sa;Password=SuaSenhaSegura;